apiVersion: argoproj.io/v1alpha1
kind: AnalysisTemplate
metadata:
  name: success-rate
spec:
  args:
  - name: service-name
  metrics:
  - name: success-rate
    interval: 5m
    successCondition: result[0] >= 0.95
    failureLimit: 3
    provider:
      prometheus:
        address: http://mimir-nginx.monitoring.svc:80/prometheus
        headers:
        - key: X-Scope-OrgID
          value: gep_sandbox
        query: |
          sum(irate(nginx_ingress_controller_requests{host="{{args.service-name}}",status!~"5.*"}[5m]))/sum(irate(nginx_ingress_controller_requests{host="{{args.service-name}}"}[5m]))
