apiVersion: argoproj.io/v1alpha1
kind: Rollout
metadata:
  name: example-rollout
spec:
  replicas: 10
  selector:
    matchLabels:
      app: nginx
  template:
    metadata:
      labels:
        app: nginx
    spec:
      containers:
      - name: nginx
        image: nginx:1.15.5
        ports:
        - containerPort: 80
  minReadySeconds: 30
  revisionHistoryLimit: 3
  strategy:
    canary:
      trafficRouting:
        # This controls how traffic is split between stable and canary.
        split:
          canaryService: example-rollout-canary
          stableService: example-rollout-stable
          weights:
            canary: 10
            stable: 90
      steps:
      - setCanaryScale:
          replicas: 3
      - pause: { duration: 10s }  # Optional pause between steps to allow time for evaluation.
      - setCanaryScale:
          replicas: 6
      - pause: { duration: 10s }
      - setCanaryScale:
          replicas: 10
