apiVersion: argoproj.io/v1alpha1
kind: Rollout
metadata:
  name: example-rollout
spec:
  replicas: 8
  selector:
    matchLabels:
      app: nginx
  template:
    metadata:
      labels:
        app: nginx
    spec:
      containers:
      - name: nginx
        image: nginx:1.15.6
        ports:
        - containerPort: 80
  minReadySeconds: 30
  revisionHistoryLimit: 3
  strategy:
    canary:
      maxSurge: 25%
      maxUnavailable: 0
      canaryService: example-rollout-canary
      stableService: example-rollout-stable
      trafficRouting:
        nginx:
          stableIngress: example-rollout-ing
      steps:
      - setCanaryScale:
          replicas: 1
      - pause: { duration: 10s }
      - setCanaryScale:
          replicas: 3
      - pause: { duration: 10s }
      - setCanaryScale:
          replicas: 5
