apiVersion: argoproj.io/v1alpha1
kind: Rollout
metadata:
  name: example-rollout
spec:
  replicas: 10
  selector:
    matchLabels:
      app: nginx
  template:
    metadata:
      labels:
        app: nginx
    spec:
      containers:
      - name: nginx
        image: nginx:1.15.6
        ports:
        - containerPort: 80
  minReadySeconds: 30
  revisionHistoryLimit: 3
  strategy:
    canary:
      trafficRouting: object
      maxSurge: "25%"
      maxUnavailable: 0
      steps:
      # 1 canary pod (10% of spec.replicas)
      - setCanaryScale:
          weight: 10
      # 90% of traffic to the 1 canary pod
      - setWeight: 90
      - pause: {}
      # - setWeight: 25
      # - pause:
      #     duration: 10s
      # - setWeight: 50
      # - pause:
      #     duration: 10s
      # - setWeight: 75
      # - pause:
      #     duration: 10s
      # - setWeight: 100
      # - pause:
      #     duration: 10s
